package com.easytoolsoft.easyreport.domain.metadata.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.easytoolsoft.easyreport.domain.metadata.example.GlobalParamExample;
import com.easytoolsoft.easyreport.domain.metadata.po.GlobalParam;

public interface GlobalParamDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ezrpt_meta_globalparam
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    long countByExample(GlobalParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ezrpt_meta_globalparam
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    int deleteByExample(GlobalParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ezrpt_meta_globalparam
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ezrpt_meta_globalparam
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    int insert(GlobalParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ezrpt_meta_globalparam
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    int insertSelective(GlobalParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ezrpt_meta_globalparam
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    List<GlobalParam> selectByExampleWithBLOBs(GlobalParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ezrpt_meta_globalparam
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    List<GlobalParam> selectByExample(GlobalParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ezrpt_meta_globalparam
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    GlobalParam selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ezrpt_meta_globalparam
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    int updateByExampleSelective(@Param("record") GlobalParam record, @Param("example") GlobalParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ezrpt_meta_globalparam
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") GlobalParam record, @Param("example") GlobalParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ezrpt_meta_globalparam
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    int updateByExample(@Param("record") GlobalParam record, @Param("example") GlobalParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ezrpt_meta_globalparam
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    int updateByPrimaryKeySelective(GlobalParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ezrpt_meta_globalparam
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(GlobalParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ezrpt_meta_globalparam
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    int updateByPrimaryKey(GlobalParam record);
}