package com.easytoolsoft.easyreport.domain.metadata.po;

import java.util.Date;

public class GlobalParam {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ezrpt_meta_globalparam.id
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ezrpt_meta_globalparam.name
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ezrpt_meta_globalparam.ds_id
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    private Integer ds_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ezrpt_meta_globalparam.create_user
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    private String create_user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ezrpt_meta_globalparam.gmt_created
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    private Date gmt_created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ezrpt_meta_globalparam.gmt_modified
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    private Date gmt_modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ezrpt_meta_globalparam.query_params
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    private String query_params;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ezrpt_meta_globalparam.id
     *
     * @return the value of ezrpt_meta_globalparam.id
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ezrpt_meta_globalparam.id
     *
     * @param id the value for ezrpt_meta_globalparam.id
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ezrpt_meta_globalparam.name
     *
     * @return the value of ezrpt_meta_globalparam.name
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ezrpt_meta_globalparam.name
     *
     * @param name the value for ezrpt_meta_globalparam.name
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ezrpt_meta_globalparam.ds_id
     *
     * @return the value of ezrpt_meta_globalparam.ds_id
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    public Integer getDs_id() {
        return ds_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ezrpt_meta_globalparam.ds_id
     *
     * @param ds_id the value for ezrpt_meta_globalparam.ds_id
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    public void setDs_id(Integer ds_id) {
        this.ds_id = ds_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ezrpt_meta_globalparam.create_user
     *
     * @return the value of ezrpt_meta_globalparam.create_user
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    public String getCreate_user() {
        return create_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ezrpt_meta_globalparam.create_user
     *
     * @param create_user the value for ezrpt_meta_globalparam.create_user
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    public void setCreate_user(String create_user) {
        this.create_user = create_user == null ? null : create_user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ezrpt_meta_globalparam.gmt_created
     *
     * @return the value of ezrpt_meta_globalparam.gmt_created
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    public Date getGmt_created() {
        return gmt_created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ezrpt_meta_globalparam.gmt_created
     *
     * @param gmt_created the value for ezrpt_meta_globalparam.gmt_created
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    public void setGmt_created(Date gmt_created) {
        this.gmt_created = gmt_created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ezrpt_meta_globalparam.gmt_modified
     *
     * @return the value of ezrpt_meta_globalparam.gmt_modified
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    public Date getGmt_modified() {
        return gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ezrpt_meta_globalparam.gmt_modified
     *
     * @param gmt_modified the value for ezrpt_meta_globalparam.gmt_modified
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    public void setGmt_modified(Date gmt_modified) {
        this.gmt_modified = gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ezrpt_meta_globalparam.query_params
     *
     * @return the value of ezrpt_meta_globalparam.query_params
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    public String getQuery_params() {
        return query_params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ezrpt_meta_globalparam.query_params
     *
     * @param query_params the value for ezrpt_meta_globalparam.query_params
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    public void setQuery_params(String query_params) {
        this.query_params = query_params == null ? null : query_params.trim();
    }
}