package com.easytoolsoft.easyreport.domain.metadata.po;

import java.util.Date;

public class GlobalParam {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ezrpt_meta_globalparam.id
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ezrpt_meta_globalparam.name
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ezrpt_meta_globalparam.ds_id
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    private Integer dsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ezrpt_meta_globalparam.create_user
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ezrpt_meta_globalparam.gmt_created
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ezrpt_meta_globalparam.gmt_modified
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ezrpt_meta_globalparam.query_params
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    private String queryParams;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ezrpt_meta_globalparam.id
     *
     * @return the value of ezrpt_meta_globalparam.id
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ezrpt_meta_globalparam.id
     *
     * @param id the value for ezrpt_meta_globalparam.id
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ezrpt_meta_globalparam.name
     *
     * @return the value of ezrpt_meta_globalparam.name
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ezrpt_meta_globalparam.name
     *
     * @param name the value for ezrpt_meta_globalparam.name
     *
     * @mbg.generated Wed Jan 11 20:39:46 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public Integer getDsId() {
        return dsId;
    }

    public void setDsId(Integer dsId) {
        this.dsId = dsId;
    }

    public String getCreateUser() {
        return createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    public Date getGmtCreated() {
        return gmtCreated;
    }

    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    public Date getGmtModified() {
        return gmtModified;
    }

    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    public String getQueryParams() {
        return queryParams;
    }

    public void setQueryParams(String queryParams) {
        this.queryParams = queryParams;
    }

  
}